apiVersion: v1
kind: Service
metadata:
  name: rekaclip-backend
  labels:
    app.kubernetes.io/name: rekaclip-backend
    app.kubernetes.io/part-of: rekaclip
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rekaclip-backend
  ports:
    - name: http
      port: 5001
      targetPort: http
