apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-deployment.yaml
  - web-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-serviceaccount.yaml
