@baseUrl = http://localhost:3000
@apiKey = sk-xxx

### ping api
POST {{baseUrl}}/api/ping
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "message": "hello"
}

### get user info
POST {{baseUrl}}/api/get-user-info
Content-Type: application/json
Authorization: Bearer {{apiKey}}


### get user credits
POST {{baseUrl}}/api/get-user-credits
Content-Type: application/json
Authorization: Bearer {{apiKey}}

### gen image
POST {{baseUrl}}/api/demo/gen-image
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "prompt": "a beautiful girl running with 2 cats",
  "provider": "replicate",
  "model": "black-forest-labs/flux-schnell"
}

### gen text 
POST {{baseUrl}}/api/demo/gen-text
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "prompt": "9.11 vs 9.8, which one is greater?",
  "provider": "openrouter",
  "model": "deepseek/deepseek-r1"
}

### send email
POST {{baseUrl}}/api/demo/send-email
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "emails": ["test@invertimage.space"],
  "subject": "Hello from Invert Image, with Resend",
  "content": "<p style='color: red;'>Hello from <a href='https://www.invertimage.space'>Invert Image</a></p>"
}



### gen outfit
POST {{baseUrl}}/api/gen-outfit
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "base_image_url": "https://pub-1929c3f9c893452bb8c09c1ad47ce906.r2.dev/upload/abd541bc-e094-46b5-9cad-b3762da44bb2_base.png",
  "description": "白色上衣"
}