apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rekaclip
resources:
  - ../../../base
patches:
  - target:
      kind: ServiceAccount
      name: rekaclip-backend
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: rekaclip-backend
        annotations:
          argocd.argoproj.io/sync-wave: "-1"
  - target:
      kind: Service
      name: rekaclip
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: rekaclip
        annotations:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Service
      name: rekaclip-backend
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: rekaclip-backend
        annotations:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Deployment
      name: rekaclip
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: rekaclip
        annotations:
          argocd.argoproj.io/sync-wave: "1"
      spec:
        template:
          metadata:
            annotations:
              rekaclip/config-revision: "2026-05-06-4"
  - target:
      kind: Deployment
      name: rekaclip-backend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: rekaclip-backend
        annotations:
          argocd.argoproj.io/sync-wave: "1"
      spec:
        template:
          metadata:
            annotations:
              rekaclip/config-revision: "2026-05-06-4"
images:
  - name: registry.144.91.77.245.sslip.io/rekaclip-web
    newName: registry.144.91.77.245.sslip.io/rekaclip-web
    newTag: production-20260506-2
  - name: registry.144.91.77.245.sslip.io/rekaclip-backend
    newName: registry.144.91.77.245.sslip.io/rekaclip-backend
    newTag: 20260506-3
