apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app
  - app-namespace.yaml
  - runtime-namespace.yaml
  - runtime-rbac.yaml
  - registry-pull.sealedsecret.yaml
  - web-env.sealedsecret.yaml
  - backend-env.sealedsecret.yaml
  - rekaclip-live.certificate.yaml
  - rekaclip-preview.certificate.yaml
  - rekaclip-live.ingress.yaml
  - rekaclip-preview.ingress.yaml
  - rekaclip-staging-placeholder.configmap.yaml
