apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: rekaclip
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    .dockerconfigjson: AgAzVFj8V4sCdscn8pC2fy5MqZopRssVoyU3LhphDAlGK8G1z809G1/QuqQC7i1ry3JOgdF2aBXBiQiRMwgpKaiAluknyKo1SSYK+u3ovarzZge1t6vKbHupzh85jh7aEkqjfeV+AihA/tHB+j2Oy9mFSZxM8Ui3xF6ftdg5MRJFgQKucBG0qLwmiWIoi/Mmlt3744AF+Kcr3M7tsbc7ZyS20sf1ugls7e/uZ1VJOdkqQJ9xY4F79tpSFGj/p/iVXLR0YD7P2xOWiLroCRUfJROqesXUuytclh6aDyd/upF6YkPHCAvkNVx1EPEGKAkUjW/Bg3Vjgwo2qAjrsuvTHEKOO5B9eKIPOCKmqXAV2cdDx7MIqCcwOFyfNFOBqh9Im6+HwN5I0Lr0cvbgbADlVwHRPSc2Ka7D/W+gkozsiWB6BIc75+M1kih6NB770clCSYNkgwsuPEI4MUVR+cAmCqBC36vrhsWygX/qTrIp23R1UJn+T7xuiZO2S7WeUfmZVnZZ1YSpwvG7ShsXEhHRGKocDmJCqUTC6zQl40uBvtd90RLWaMj5l/ZY/8EI4pBMBplQIOiClAZmp4oVZD67sHv0pZNyiNonsyz6KzCh4L9DeEq+XEv3Mucgx9NK1dQqy3emXmxVRwjcHjgIa9o9I344kUg2uh3TnCbjfnnk3nAtrHhQgVoUWSeM0ZvFKRlV0M8r5V4ag7BiWWo1oms2r30TRkpUwQvxfs9Bz2PjspN3tDfH2WvULuJnb5BrqwqMwcj10Br8qf/iGpTubSxQrj645tDk2pECy3/NEgCbpB3EIKrq1KjhI3vu9ex0s8jeNesdwkLuqhQU7RoxOn2z9H32FauQp4scRDc6aZv+V8LRSFSszeIn5SLh4VbhVCTtI1/S4I9HH3LaiaMQ7ZFkSObXKGhtKaBRB2FjPdl9/Xs8AUNE8z5VukGG
  template:
    metadata:
      labels:
        sealedsecrets.bitnami.com/managed: 'true'
      name: dokploy-fleet-ghcr
      namespace: rekaclip
    type: kubernetes.io/dockerconfigjson
