apiVersion: v1
kind: Secret
metadata:
  name: supabase-source-secret
  namespace: supabase-db
type: Opaque
stringData:
  host: ${SUPABASE_SOURCE_HOST}
  port: "${SUPABASE_SOURCE_PORT}"
  dbname: ${SUPABASE_SOURCE_DB}
  user: ${SUPABASE_SOURCE_USER}
  password: ${SUPABASE_SOURCE_PASSWORD}
  sslmode: ${SUPABASE_SOURCE_SSLMODE}
