apiVersion: v1
kind: Secret
metadata:
  name: supabase-backup-secret
  namespace: supabase-db
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  ACCESS_KEY_ID: ${BACKUP_ACCESS_KEY_ID}
  ACCESS_SECRET_KEY: ${BACKUP_SECRET_ACCESS_KEY}
