apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: supabase-pg-daily
  namespace: supabase-db
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: supabase-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
