apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: supabase-pg-initial
  namespace: supabase-db
spec:
  cluster:
    name: supabase-pg
  target: prefer-standby
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
