apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app
  - app-namespace.yaml
  - runtime-namespace.yaml
  - runtime-rbac.yaml
  - registry-pull.sealedsecret.yaml
  - web-env.sealedsecret.yaml
  - backend-env.sealedsecret.yaml
  - rekaclip-staging.certificate.yaml
  - rekaclip-staging.ingress.yaml
