apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: rekaclip-staging
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    .dockerconfigjson: AgBnnjE877IjuqIey6GnDw7a4mk5wrnPOO2olOrj5Xoay4OIbBnjhsDRDwwhuvoyBO47AD9R2FjegkQtrugBJwM4OfJC2tNQAvSmB/6pllv0l3Cp8p4AiyzOgH0kem5ar4Vj7b+g7/9mMyG0o2xTu4qx+Y1Wr/kJ+R32DJJ+yPsjMk8mXF+CYvwvRzO5vAJ3rVQHSpPPgiclTXU7csWJWd/ngsZsS+L5Nggtp0TVy0THHj5tgyyoneLIvmDVHHlhWddO202IEF2xkgy0QTOgiuEB5pKP3C46lsRwP4IlGJ1JtNiqLtc2uyqiRp1g5xd7mUQFPnSsrcHhHdIabVxutoiolZPHI0kQAp1qA4pquyp2BzxDEkhVyIMr/nh0sQ1vVE4aFJVHwWqLmPg4hdPip50ZRY4A4fpVldYmLCKqPYJDogfsEqh1ut5FGQLyu/+5nnc1PvnbBR51TxiPSCv1ruofhrEJmJgDuO0cqOHH5JiYFNswJG0B960+eeTAfGFcQCBQV0uYdSAjOR4ZxMWXrTHFefYySITOTjYNjJ+d0+Ljk8iYkjNmcJQ7DiFTjTyAlEVICWUrHaBsraxTykJLFvHhfK30FVd7AmTjSyYMTHALbc+Q7iR5Ae+3xI/woZjXH2UuSw6MR5/gK/xgGTJKNN7+cVBuAT2y7cBn1C29Pb8QH9bK0fdwqM3XEKWvRIq/VC60OL6VI464mHzMxO9How10pLxvA32hUj6mVPuyPw3x3D0C0RNhhe9nxGuiqcbtUZuz/L1HDiTgkADY01N9HZILoXYxDDBo1tZnv25Ec4htfFvAz0x1hbxFGuL2yeSXnRpr0kV34C10yHrFIJDGzU+gmA8OjX3Plqnz0RhKb5Zx0K39HvvmiBbbshlKcZbYSu20M+N7aQewVCgUrbndvlZwwc+gKaHgaP+hA9VsjUaMNQ3xpTz3bCme
  template:
    metadata:
      labels:
        sealedsecrets.bitnami.com/managed: 'true'
      name: dokploy-fleet-ghcr
      namespace: rekaclip-staging
    type: kubernetes.io/dockerconfigjson
