apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rekaclip-staging-tls
  namespace: rekaclip-staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: rekaclip-staging-tls
  dnsNames:
    - staging.rekaclip.homes
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-cloudflare
